spring.application.name=davilaAPI

spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/davilaAPI}
spring.datasource.username=${DATASOURCE_USERNAME:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD:yannick2007}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.web.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET:12345678}